removed polybar shadows

diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -1,10 +1,11 @@
-#!/bin/bash
+#!/bin/sh
 
-if [ -z $(command -v stow) ] 
-then
-    echo "stow not installed, please install it to proceed."
-else
-	for i in */ do
-		stow $i
-	done
+# ensure stow is installed
+if ! command -v stow > /dev/null; then
+    echo 'error : install stow first' >&2
+    exit 1
 fi
+
+for i in */; do
+    stow "$i" -t ~
+done
